---
#This is my Host section
- hosts: 84.39.48.14
#This is my task section
  tasks:
    - name: NTP installation
      yum: name=ntp state=present
    - name: NTP service
      service: name=ntpd state=started enabled=yes
